apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus
spec:                          # Deployment spec
  replicas: 1
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      labels:
        app: prometheus
    spec:                      # Pod spec (different from Deployment spec)
      containers:              # belongs to pod spec
      - name: prometheus
        image: prom/prometheus:latest
        ports:
        - containerPort: 9090
        volumeMounts:
        - name: prom-volume
          mountPath: /etc/prometheus
      volumes:                 # belongs to pod spec
      - name: prom-volume
        configMap:
          name: prometheus-config